### ISSUE TITLE
Navbar is not responsive

### ISSUE THREAD

**Issue by 5thComrade** [5thComrade/mailbuddy#12]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I have provided sufficient information below to help reproduce this issue.

### Summary

The Navbar is currently un-responsive. We need to make it responsive to ensure that the mobile users have a good experience using the app.
The Sign In and Sign for free buttons should be hidden on mobile view and instead should show a log-in icon using the lucid-react icons(https://lucide.dev/icons/log-in).

### Expected Behavior

Make the navbar responsive

### Current Behavior

Navbar not responsive

### Is this a regression?

- [ ] Yes, this used to work in a previous version.

### Debug info

- Node version:
- Operating System:
- Browser:

**Comment by varunk20081998** [comment]
will start working on this
